// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// restore --no-dependencies  /p:UseSharedCompilation=false took 2.5s and exited with 0
// build --framework netcoreapp2.0 --configuration Release --no-restore --no-dependencies  /p:UseSharedCompilation=false took 5.05s and exited with 0
// ***** Done, took 00:00:07 (7.97 sec)   *****
// Found benchmarks:
//   ChipotleCsvBenchmark.Parse2KB: DefaultJob
//   ChipotleCsvBenchmark.Parse4KB: DefaultJob
//   ChipotleCsvBenchmark.Parse8KB: DefaultJob
//   ChipotleCsvBenchmark.Parse16KB: DefaultJob
//   ChipotleCsvBenchmark.Parse32KB: DefaultJob

// **************************
// Benchmark: ChipotleCsvBenchmark.Parse2KB: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// BeforeAnythingElse
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob
OverheadJitting  1: 1 op, 868200.00 ns, 868.2000 us/op
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at Chipotle.CSV.Csv..ctor(Stream stream, Pipe pipe) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\src\Csv.cs:line 29
   at test.ChipotleCsvBenchmark.<ParseCsvFile>d__9.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\ChipotleCsvBenchmark.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at test.ChipotleCsvBenchmark.<Parse2KB>d__2.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\ChipotleCsvBenchmark.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkDotNet.Autogenerated.Runnable_0.<.ctor>b__3_4() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 175
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 477
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 154
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 70
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: ChipotleCsvBenchmark.Parse4KB: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// BeforeAnythingElse
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob
OverheadJitting  1: 1 op, 795300.00 ns, 795.3000 us/op
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at Chipotle.CSV.Csv..ctor(Stream stream, Pipe pipe) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\src\Csv.cs:line 29
   at test.ChipotleCsvBenchmark.<ParseCsvFile>d__9.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\ChipotleCsvBenchmark.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at test.ChipotleCsvBenchmark.<Parse4KB>d__3.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\ChipotleCsvBenchmark.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkDotNet.Autogenerated.Runnable_1.<.ctor>b__3_4() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 818
   at BenchmarkDotNet.Autogenerated.Runnable_1.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 1120
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 797
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\bin\release\netcoreapp2.0\0748aadc-2e60-4e36-8e19-4d5b0ec85599\0748aadc-2e60-4e36-8e19-4d5b0ec85599.notcs:line 70
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: ChipotleCsvBenchmark.Parse8KB: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// BeforeAnythingElse
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob
OverheadJitting  1: 1 op, 808700.00 ns, 808.7000 us/op
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at Chipotle.CSV.Csv..ctor(Stream stream, Pipe pipe) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\src\Csv.cs:line 29
   at test.ChipotleCsvBenchmark.<ParseCsvFile>d__9.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\Benchmarks\ChipotleCsvBenchmark.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at test.ChipotleCsvBenchmark.<Parse8KB>d__4.MoveNext()