// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Building 1 exe(s) in Parallel: Start   *****
Unable to find .sln file. Will use current directory C:\Users\ryzng\Source\Repos\Chipotle.CSV\test to search for project file. If you don't use .sln file on purpose it should not be a problem.
// restore --no-dependencies  /p:UseSharedCompilation=false took 5.54s and exited with 0
// build --framework netcoreapp2.0 --configuration Release --no-restore --no-dependencies  /p:UseSharedCompilation=false took 9.04s and exited with 0
// ***** Done, took 00:00:15 (15.02 sec)   *****
// Found benchmarks:
//   CsvParsing.ParseCsv: DefaultJob

// **************************
// Benchmark: CsvParsing.ParseCsv: DefaultJob
// *** Execute ***
// Launch: 1 / 1
// BeforeAnythingElse
// Benchmark Process Environment Information:
// Runtime=.NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT
// GC=Concurrent Workstation
// Job: DefaultJob
OverheadJitting  1: 1 op, 1262500.00 ns, 1.2625 ms/op
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Chipotle.CSV.Csv.<GetNextAsync>d__15.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\src\Csv.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at test.CsvParsing.<ParseCsv>d__3.MoveNext() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\test\CsvParsing.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BenchmarkDotNet.Autogenerated.Runnable_0.<.ctor>b__3_4() in C:\Users\ryzng\Source\Repos\Chipotle.CSV\test\bin\release\netcoreapp2\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e.notcs:line 165
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\test\bin\release\netcoreapp2\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e.notcs:line 467
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\test\bin\release\netcoreapp2\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e.notcs:line 144
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\ryzng\Source\Repos\Chipotle.CSV\test\bin\release\netcoreapp2\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e\aa85c7c1-4e58-41d8-8e59-a59b4ccb654e.notcs:line 60
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\test.CsvParsing-report.csv
  BenchmarkDotNet.Artifacts\results\test.CsvParsing-report-github.md
  BenchmarkDotNet.Artifacts\results\test.CsvParsing-report.html

// * Detailed results *
CsvParsing.ParseCsv: DefaultJob
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.11.0, OS=Windows 10.0.17134.191 (1803/April2018Update/Redstone4)
Intel Core i7-8650U CPU 1.90GHz (Max: 1.91GHz) (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=2.1.302
  [Host] : .NET Core 2.0.9 (CoreCLR 4.6.26614.01, CoreFX 4.6.26614.01), 64bit RyuJIT


   Method | Mean | Error | Min | Max | Median | Allocated |
--------- |-----:|------:|----:|----:|-------:|----------:|
 ParseCsv |   NA |    NA |  NA |  NA |     NA |       N/A |

Benchmarks with issues:
  CsvParsing.ParseCsv: DefaultJob

// * Warnings *
Environment
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Windows Defender (windowsdefender://)
Use InProcessToolchain to avoid new process creation.


// * Legends *
  Mean      : Arithmetic mean of all measurements
  Error     : Half of 99.9% confidence interval
  Min       : Minimum
  Max       : Maximum
  Median    : Value separating the higher half of all measurements (50th percentile)
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 ns      : 1 Nanosecond (0.000000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
Run time: 00:00:04 (4.79 sec), executed benchmarks: 1

// * Artifacts cleanup *
